Traceback (most recent call last):
  File "/home/znazari/ppmi_files/best_feature/easy/hi.py", line 1, in <module>
Traceback (most recent call last):
  File "/home/znazari/ppmi_files/best_feature/easy/hi.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/znazari/ppmi_files/best_feature/easy/hi.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "/home/znazari/ppmi_files/best_feature/easy/hi.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[65092,1],1]
  Exit code:    1
--------------------------------------------------------------------------
