mpiexec (OpenRTE) 3.1.4

Report bugs to http://www.open-mpi.org/community/help/
Traceback (most recent call last):
  File "hi1.py", line 2, in <module>
    from dask_mpi import initialize
ModuleNotFoundError: No module named 'dask_mpi'
Traceback (most recent call last):
  File "hi1.py", line 2, in <module>
    from dask_mpi import initialize
ModuleNotFoundError: No module named 'dask_mpi'
Traceback (most recent call last):
  File "hi1.py", line 2, in <module>
    from dask_mpi import initialize
ModuleNotFoundError: No module named 'dask_mpi'
Traceback (most recent call last):
  File "hi1.py", line 2, in <module>
    from dask_mpi import initialize
ModuleNotFoundError: No module named 'dask_mpi'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38281,1],2]
  Exit code:    1
--------------------------------------------------------------------------
