Traceback (most recent call last):
  File "/home/znazari/ppmi_files/proteomic_best/parallel_best_proteomic.py", line 56, in <module>
    X_train, X_test, y_train, y_test = train_test_split(dd.from_pandas(X, npartitions=10), y_encoded, test_size=0.3, random_state=42)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2585, in train_test_split
    return list(
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2587, in <genexpr>
    (_safe_indexing(a, train), _safe_indexing(a, test)) for a in arrays
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 354, in _safe_indexing
    return _pandas_indexing(X, indices, indices_dtype, axis=axis)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 196, in _pandas_indexing
    return X.take(key, axis=axis)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/dask/dataframe/core.py", line 5143, in __getattr__
    raise AttributeError("'DataFrame' object has no attribute %r" % key)
AttributeError: 'DataFrame' object has no attribute 'take'
