joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/parallel.py", line 289, in <listcomp>
    for func, args, kwargs in self.items]
TypeError: cannot unpack non-iterable method object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/znazari/ppmi_files/proteomic_best/joblib/best_proteomic.py", line 111, in <module>
    selector = Parallel(n_jobs=-1)(delayed(selector.fit)(X_train, y_train))
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/znazari/anaconda3/envs/Zainab-env/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: cannot unpack non-iterable method object
